### PR TITLE
feat: add option to add default locale

### PR DESCRIPTION
**Pull request by jreppnow**

### CODE REVIEW

**Review by tronicboy1 — APPROVED** [review]
I like this! You may be right that [add_resource_overriding](https://docs.rs/fluent/latest/fluent/bundle/struct.FluentBundle.html#method.add_resource_overriding) might do it but I think its much better to have a convenience behavior like this. If you were to add a German l10n, it would be cool to have it automatically go to the English version.

Maybe it might be a good idea to log something to tracing debug if the FTL key was missing from the target locale? That might make it easier to debug.

**Comment by jreppnow** [comment]
@tronicboy1 I think it would be more flexible to change this line into `add_resource_overriding` (should be backwards-compatible, as this was a hard error before, although it does change behavior): https://github.com/tronicboy1/axum_l10n/blob/f179928f94ad0f6fa6a8835a9e7ef53045982198/src/fluent.rs#L91

Reason: By doing this, you can have multiple back-ups, instead of just one.

**Comment by tronicboy1** [comment]
@jreppnow 
That's a very good idea too! I don't see an issue with allowing the override behavior. 

Yes it is a behavior change but not a breaking change so I think it's fair game. You're more than welcome to make another PR for that change!

**Comment by jreppnow** [comment]
As discussed, superseded by #2.

**Pull request closed without merging**
